### ISSUE TITLE
Align vocabulary with status list draft

### ISSUE THREAD

**Issue by OR13** [peppelinux/draft-demarco-oauth-status-assertions#81]
Add registry entries for valid and invalid.

Enable assertion to include those values along with potential credentials type specific fresh information.

See: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-status-list-03#section-14.2

**Comment by marinaado** [comment]
This PR is related to the issues pointed in the https://github.com/peppelinux/draft-demarco-oauth-status-assertions/pull/61, i.e. : 
- reconsider the credential_status_validity boolean parameter
- consider alignment of the credential_status_detail parameter vocabulary with the statusPurpose parameter of OAuth Status Lists specification.

**Comment by peppelinux** [comment]
@OR13 can you confirm that this issue was resolved https://github.com/peppelinux/draft-demarco-oauth-status-assertions/pull/61

I remember to have asked the merge of PR 61 and to continue working on the additional value/terms alignements using a separate issue, as opend by you. While, at the end, we got all the required updates in PR 61 and this seems enough

I close this issue and if I made a mistake please re-open this with the motivation
